-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.library
(

    CONSTRAINT library_pkey PRIMARY KEY (libraryid)
);

CREATE TABLE IF NOT EXISTS public.literature
(

    CONSTRAINT literature_pkey PRIMARY KEY (literatureid)
);

CREATE TABLE IF NOT EXISTS public.literatureissued
(

    CONSTRAINT literatureissued_pkey PRIMARY KEY (issueid)
);

CREATE TABLE IF NOT EXISTS public.readers
(

    CONSTRAINT readers_pkey PRIMARY KEY (readerid)
);

CREATE TABLE IF NOT EXISTS public.readingrooms
(

    CONSTRAINT readingrooms_pkey PRIMARY KEY (roomid)
);

ALTER TABLE IF EXISTS public.literature
    ADD CONSTRAINT literature_readingroomid_fkey FOREIGN KEY (readingroomid)
    REFERENCES public.readingrooms (roomid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.literatureissued
    ADD CONSTRAINT literatureissued_literatureid_fkey FOREIGN KEY (literatureid)
    REFERENCES public.literature (literatureid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.literatureissued
    ADD CONSTRAINT literatureissued_readerid_fkey FOREIGN KEY (readerid)
    REFERENCES public.readers (readerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.readingrooms
    ADD CONSTRAINT readingrooms_libraryid_fkey FOREIGN KEY (libraryid)
    REFERENCES public.library (libraryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;